/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.view;

import edu.neu.csye6200.controller.GroupHelper;
import edu.neu.csye6200.model.Classroom;
import edu.neu.csye6200.model.Group;
import edu.neu.csye6200.model.Student;

import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 * @author sid
 *
 */
public class ClassroomUI extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    List<Group> grouplist;
    String classroomId, groupId,groupCount,studentCount,teacherAssigned;
    public ClassroomUI() {
        initComponents();
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoCreateColumnsFromModel(true);
//        try {
//        	System.out.println("Showing Class romm and group info:");
//        	fetchClassRoomGroupInfo((DefaultTableModel)jTableClassroomInfo.getModel())
//        	.addRow(new Object[]{classroomId,groupId,groupCount,studentCount,teacherAssigned});
//		} catch (Exception e) {
//			e.printStackTrace();
//		}
    }
     public ClassroomUI(List<Classroom> classrooms) {
        initComponents();
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoCreateColumnsFromModel(true);

        DefaultTableModel model = (javax.swing.table.DefaultTableModel)jTable1.getModel(); 
        System.out.println("Showing Class romm and group info:");
        try {
        	fetchClassRoomGroupInfo(model,classrooms);
		} catch (Exception e) {
			e.printStackTrace();
		}
        model.addRow(new Object[]{groupId, classroomId, teacherAssigned, studentCount});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelClassroomtitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1256, 550));
        setMinimumSize(new java.awt.Dimension(1256, 550));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1456, 70));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        jLabelClassroomtitle.setBackground(new java.awt.Color(204, 204, 255));
        jLabelClassroomtitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelClassroomtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClassroomtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/classroom1.PNG"))); // NOI18N
        jLabelClassroomtitle.setText("Classroom Info");
        jLabelClassroomtitle.setToolTipText("");
        jLabelClassroomtitle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClassroomtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(618, 618, 618))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelClassroomtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Classroom ID", "Group ID", "Teacher Name", "Student Name"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Classroom ID");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Group ID");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Teacher Name");
            jTable1.getColumnModel().getColumn(3).setMinWidth(400);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(400);
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Student Name");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassroomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassroomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassroomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassroomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassroomUI().setVisible(true);
            }
        });
    }
    
    private DefaultTableModel fetchClassRoomGroupInfo(DefaultTableModel model,List<Classroom> classrooms) throws Exception {

        //JTableHeader th = new JTableHeader();
        
        model.setRowCount(0);
        for (Classroom classroom : classrooms) {
            Object[] row = new Object[4];
            row[0] = classroom.getClassId();
            for(Group group : classroom.getGroups()){
                 row[1] = group.getGroupId();
                 row[2] = group.getTeacher().getFirstName()+" "+group.getTeacher().getLastName();
                 for(Student stud : group.getStudents()){
                     row[3] = stud.getFirstName()+" "+stud.getLastName()+" "+"(Age :"+stud.getAge()+")";
                      model.addRow(row);
                 }
            }
            
        }
        return model;
        //GroupHelper helper = new GroupHelper();
       
//        List<Group>	 groups = helper.getClassRoomGroupInfo();
//        for (Group group : groups) {
//            System.out.println(group.getGroupId());
//            Object[] row = new Object[4];
//            row[0] = group.getGroupId();
//            row[1] = group.getClassId();
//            row[3] = group.getTeacherId();
//            row[2] = group.getStudentsEnrolled();
//            model.addRow(row);
//
//        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClassroomtitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
